sudo: false
language: node_js
node_js:
  - "lts/*"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
    - node_js: "lts/*"
      env: TEST_SUITE=karma
env:
  matrix:
    - TEST_SUITE=unit
script: npm run $TEST_SUITE

before_install:
  - if [ ${TEST_SUITE}=="karma" ]; then
       export CHROME_BIN=chromium-browser;
       export DISPLAY=:99.0;
       sh -e /etc/init.d/xvfb start;
    fi
  